included:
  - "German Neo"
  - "German NeoTests"
  - "Neo Keyboard"

excluded:
  - Pods

vertical_whitespace:
  max_empty_lines: 2

type_name:
  excluded:
    - ContentView_Previews
    - iPhoneNeoKeyboardLayoutService
